version: '3'
services:

  mysql-db:
    image: mysql:5.7
    hostname: mysql-db
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: userpass
    volumes:
      - ./database/dumps:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/mysql
   networks:
      - mysql-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    hostname: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment: 
      PMA_HOST: mysql-db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: userpass
    networks:
      - mysql-net
    depends_on:
      - mysql-db
    ports:
      - "8085:80"

  webapp:
    image: abassi/nodejs-server
    hostname: webapp
    container_name: webapp
    restart: always
    environment: 
    volumes:
    networks:
      - mysql-net
    depends_on:
      - mysql-db
    ports: 
      - "3000:8000"
    command: node ws/index.js

networks:
  mysql-net:
    driver: bridge